version: 0.1

phases:
  pre_build:
    commands:
      - sudo npm cache clean -f
      - sudo npm install -g n
      - sudo n stable
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - images/*
    - styles/*
    - dist/bundle.js
    - resume/*
